steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull gcr.io/spartan-context-379412/ga-house:latest || exit 0']
# Build the container image
- name: gcr.io/cloud-builders/docker
  args: ['build',
   '-t', 'gcr.io/spartan-context-379412/ga-house:latest',
               '--cache-from', 'gcr.io/spartan-context-379412/ga-house:latest',
    '.']
  id: Building the container image
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/spartan-context-379412/ga-house:latest']
  id: Pushing the image to registry
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'ga-house', '--image', 'gcr.io/spartan-context-379412/ga-house:latest', '--region', 'us-central1']