import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import axios from "axios";
import { useState } from 'react';
import { QueryClient, useQuery, QueryClientProvider } from "react-query"
import { ReactQueryDevtools } from "react-query/devtools"
import PopUp from "./popUp"
export default function PopUpFunction() {
  const { popUpFunction } = PopUp();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js"></script>
      </Head>
      <button onClick={() => { popUpFunction() }}>Click me</button>
    </>
  )
}